// LanguageMappings.js
const languageMappings = {
  '/en': '/',
  '/en/services/immigration-lawyer': '/servicios/abogado-de-inmigracion',
  '/en/services': '/servicios',
  '/en/attorneys': '/abogados',
  '/en/about-us': '/nosotros',
  '/en/vawa-visa': '/visa-vawa',
  '/en/t-visa': '/visa-t',
  '/en/u-visa': '/visa-u',
  '/en/k1-visa': '/visa-k1',
  '/en/testimonios': '/testimonios',
  '/en/blog': '/blog',
  '/en/contact': '/contacto',
  '/en/reviews': '/testimonios',
  '/en/terms-and-conditions': '/terminos-y-condiciones',
  '/en/privacy-policy': '/politica-de-privacidad',
  '/en/sitemap': '/mapa-de-sitio',
  '/en/as-seen-live-with-chiquis': '/transmisiones-en-vivo-con-chiquis',
  '/en/thank-you': '/gracias',
  '/en/attorneys/maria-mendoza': '/abogados/maria-mendoza',
  
  '/': '/en',
  ' ': '/en',
  '/servicios/abogado-de-inmigracion': '/en/services/immigration-lawyer',
  '/servicios': '/en/services',
  '/abogados': '/en/attorneys',
  '/nosotros': '/en/about-us',
  '/visa-vawa': '/en/vawa-visa',
  '/visa-t': '/en/t-visa',
  '/visa-u': '/en/u-visa',
  '/visa-k1': '/en/k1-visa',
  '/testimonios': '/en/testimonios',
  '/blog': '/en/blog',
  '/contacto': '/en/contact',
  '/testimonios': '/en/reviews',
  '/terminos-y-condiciones': '/en/terms-and-conditions',
  '/politica-de-privacidad': '/en/privacy-policy',
  '/mapa-de-sitio': '/en/sitemap',
  '/transmisiones-en-vivo-con-chiquis': '/en/as-seen-live-with-chiquis',
  '/gracias': '/en/thank-you',
  '/abogados/maria-mendoza': '/en/attorneys/maria-mendoza',
};


export default languageMappings;
